### ISSUE TITLE
Port to Python 3.

### ISSUE THREAD

**Issue by ghost** [makson96/Dynamics#26]
We should move to Python 3 as soon as PyMOL would do this step.

**Comment by makson96** [comment]
It seems that PyMOL 2.x builds fine with Python3. We should now be unblock to solve this issue.

**Comment by makson96** [comment]
We should implement Python3 support in the way it stays compatible with Python2 for now. Use this for the print:
https://triangle717.wordpress.com/tutorials/python/2a3printinput/
