### ISSUE TITLE
Implement ToolTip by Pmw.Balloon

### ISSUE THREAD

**Issue by tomaszmakarewicz** [makson96/Dynamics#34]
Pmw is part of PyMOL, so it shouldn't be a problem. Simple example is here:
http://www.gossamer-threads.com/lists/python/python/105209
(root.mainloop()) at the end is missing.

This should me specially helpful for configuration options.

**Comment by makson96** [comment]
PyMOL has migrated to PyQt. Any more investment in Tk won't happen.
